<?php
/**
 * @file
 * Code for the CA Staff feature.
 */

include_once('ca_staff.features.inc');

/**
 * Implements hook_menu()
 */
function ca_staff_menu() {
/**  $items['admin/config/worx_features'] = array(
    'title' => 'Worx Features',
    'description' => 'Configure Worx Features',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );*/
  $items['admin/config/worx_features/staff'] = array(
    'title' => 'Staff Configuration',
    'description' => 'Override settings for ca_staff',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_staff_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_staff.admin.inc',
    'file path' => drupal_get_path('module', 'ca_staff'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/staff/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_staff',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_staff_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_staff.admin.inc',
    'file path' => drupal_get_path('module', 'ca_staff'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_staff_menu_alter(&$items) {
  $items['staff']['title'] = variable_get('ca_staff_menu_title', 'Staff');
}